kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: {{ cluster }}
nodes:
{% for master in range (0, masters) %}
- role: control-plane
{% endfor %}
{% for worker in range (0, workers) %}
- role: control-plane
{% endfor %}
{% if feature_gates %}
featureGates:
{% for feature_gate in feature_gates %}
 "{{ feature_gate }}": true
{% endfor %}
{% endif %}
networking:
  apiServerAddress: "127.0.0.1"
  disableDefaultCNI: {{ disable_default_cniÂ }}
{% if ipv6 or dualstack %}
  ipFamily: {{ "dual" if dualstack else "ipv6" }}
{% endif %}
