parameters:
 baseplan: kcli_plan.yml
 kubevirt_version: latest
 cdi: true
 cdi_version: latest
 ui: true
 ui_version: v1.3-9
 install_kcli: false

kubevirt:
 template: {{ template }}
 numcpus: 2
 memory: 8192
 domain: {{ domain }}
 nets:
  - default
 disks:
  - size: 50
 pool: default
 files:
  - path: /etc/yum.repos.d/kubernetes.repo
    origin: kubernetes.repo
  - kubevirt_ui.yml
{% if nfs %}
  - path: /root/nfs.yml
    origin: nfs.yml
  - path: /root/nfs.sh
    origin: nfs.sh
{% endif %}
 scripts: 
  - pre.sh
  - kubernetes.sh
  - dashboard.sh
  - kubevirt.sh
{% if cdi %}
  - cdi.sh
{% endif %}
{% if ui %}
  - kubevirt_ui.sh
{% endif %}
{% if install_kcli %}
  - install_kcli.sh
{% endif %}
