name: OPENSHIFT-NIGHTLY-CI
on:
  schedule:
    - cron: '01 18 * * *'

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 PLAN: ci
 PULLSECRET: /root/openshift_pull.json

jobs:
  deploy-openshift:
    if: github.repository == 'karmab/kcli'
    strategy:
      fail-fast: false
      matrix:
        provider: [libvirt, vsphere]
    runs-on: ${{ matrix.provider }}
    steps:
     - uses: actions/checkout@v2
     - run: git pull origin ${GITHUB_REF##*/}
     - name: Install kcli
       run: curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | bash
     - name: Deploy Openshift on ${{ matrix.provider }}
       run: kcli create cluster openshift --paramfile openshift-ci-paramfiles/${{ matrix.provider }}.yml -P pull_secret=$PULLSECRET $PLAN-${{ matrix.provider }} --force
     - name: Clean everything
       if: always()
       run: kcli delete plan --yes $PLAN-${{ matrix.provider }}
